steps:
  - id: 'Get cluster credentials'
    name: 'gcr.io/k8s-skaffold/skaffold:v1.12.1' 
    args: 
      [
        "gcloud", "container", "clusters", "get-credentials", 
        "--zone", "$_ZONE",
        "--project", "$PROJECT_ID",
        "$_CLUSTER"
      ]
  - id: 'Decrypt secrets'
    name: 'gcr.io/k8s-skaffold/skaffold:v1.12.1'
    args:
      [
          "./deployment/decrypt.sh"
      ]
  - id: 'Deploy application to cluster'
    name: 'gcr.io/k8s-skaffold/skaffold:v1.12.1'
    args: 
      [
        "skaffold", "run",
      ]

substitutions:
  _ZONE: us-central1-a
  _CLUSTER: fyne-industries

