apiVersion: v1
kind: Service
metadata:
  labels:
    app: accordopartners
  name: accordopartners
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: accordopartners
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accordopartners
  labels:
    app: accordopartners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accordopartners
  template:
    metadata:
      labels:
        app: accordopartners
    spec:
      containers:
        - image: 'gcr.io/compliance-167400/accordopartners'
          name: accordopartners
          ports:
            - containerPort: 3000
              name: accordopartners
